package datn.qlth.service;

public interface CSVConstant {
	String FILETYPE = "text/csv;charset=utf-8";
	String CONTENT_DISPOSITION = "Content-Disposition";
	String FILE_NAME_ACCOUNT_LIST = "attachment; filename=\"AccountList.csv\"";
	String FILE_NAME_STUDENT_LIST = "attachment; filename=\"StudentList.csv\"";
	String FILE_NAME_TRANSCRIPT = "attachment; filename=\"Transcript.csv\"";
	String FILE_NAME_STUDENT_IN_CLASS = "attachment; filename=\"StudentInClass.csv\"";
	String FILE_NAME_FACULTY_LIST = "attachment; filename=\"FacultyList.csv\"";
	String NO = "STT";
	String USER_CODE = "Mã Sinh Viên";
	String FULL_NAME = "Tên Sinh viên";
	String FIRST_NAME = "Họ Đệm";
	String LAST_NAME = "Tên";
	String DISPLAY_NAME = "Display Name";
	String EMAIL_ADDRESS = "Email";
	String USERNAME = "Username";
	String PHONE = "Số Điện Thoại";
	String GENDER = "Giới Tính";
	String CREATE_DATE = "Ngày Tạo";
	String STATUS = "Trạng Thái";
	String ROLE = "Role";
	String FILE_NAME_GROUP_LIST = "attachment; filename=\"GroupList.csv\"";
	String REGULAR_POINT1 = "Điểm Thường Xuyên 1";
	String REGULAR_POINT2 = "Điểm Thường Xuyên 2";
	String MIDTERM_SCORE = "Điểm Giữa Kỳ";
	String FINAL_SCORE = "Điểm Cuối Kỳ";
	String BIRTH_DAY = "Ngày Sinh";
	String HOME_TOWN = "Quê Quán";
	String CLASSROOM_NAME = "Tên Lớp";
	String FACULTY_CODE = "Mã Khoa";
	String FACULTY_NAME = "Tên Khoa";
	String MAJOR_NAME = "Tên Ngành";
	String MAJOR_CODE = "Mã Ngành";
	String SUBJECT_CODE = "Mã Môn";
	String SUBJECT_NAME = "Tên Môn";
	String NUMBER_OF_CREDIT = "Số Tín Chỉ";
	String NUMBER_REGISTER = "Số Lượng Đăng Ký";
	String MAX_NUMBER_REGISTER = "Giới Hạn Đăng Ký";
	String TEACHER_NAME = "Tên Giáo Viên";
	String STATUS_REGISTER = "Trạng Thái Đăng Ký";
	String CLASSROOM_CODE = "Mã Lớp";
	String CLASSROOM_QUANTITY = "Số Lượng";
	String COURSE = "Khóa";
	String CREATED_DATE = "Ngày Táo";
	String TEACHER_CODE = "Mã Giáo Viên";
	String SPECIALIZE_LEVEL = "Trình Độ";
};

