const routes = {
    home: "/",
    profile: "/profile",
    manager: "/manager",
    login: "/login",
    feedback: "/feedback",
    forgotPassword: "/forgot-password",
    managerFaculty: "/admin/manager-faculties",
    managerMajor: "/admin/manager-majors",
    managerSubject: "/admin/manager-subjects",
    managerClassroom: "/admin/manager-class-rooms",
    managerUsers: "/admin/manager-users",
    managerAdmins: "/admin/manager-admins",
    managerTeachers: "/admin/manager-teachers",
    changePassword: "/change-password",
    introduce: "/introduce",
    contactUs: "/contact-us",
    servicePage: "/service",
    documentPage: "/documents",
    adminDetailClassRoom: "/detail-classroom/:classRoomID",
    adminDetailSubject: "/detail-subject/:subjectID",
    studyResult: "/student/study-results",
    registrationSubject: "/student/registration-subject",
};

export default routes;
