// token & login
export const TOKEN_INFO = "TOKEN_INFO";
export const USER_LOGIN_INFO = "USER_LOGIN_INFO";

// user
export const GET_LIST_USER = "GET_LIST_USER";
export const UPDATE_USER = "UPDATE_USER";
export const DELETE_USER = "DELETE_USER";
export const ADD_USER = "ADD_USER";

// teacher
export const GET_LIST_TEACHER = "GET_LIST_TEACHER";
export const UPDATE_TEACHER = "UPDATE_TEACHER";
export const DELETE_TEACHER = "DELETE_TEACHER";
export const ADD_TEACHER = "ADD_TEACHER";

//profile
export const GET_PROFILE = "GET_PROFILE";
export const UPDATE_PROFILE = "UPDATE_PROFILE";

// faculty
export const GET_LIST_FACULTY = "GET_LIST_FACULTY";
export const UPDATE_FACULTY = "UPDATE_FACULTY";
export const DELETE_FACULTY = "DELETE_FACULTY";
export const ADD_FACULTY = "ADD_FACULTY";

// major
export const GET_LIST_MAJOR = "GET_LIST_MAJOR";
export const UPDATE_MAJOR = "UPDATE_MAJOR";
export const DELETE_MAJOR = "DELETE_MAJOR";
export const ADD_MAJOR = "ADD_MAJOR";

// classroom
export const GET_LIST_CLASSROOM = "GET_LIST_CLASSROOM";
export const UPDATE_CLASSROOM = "UPDATE_CLASSROOM";
export const DELETE_CLASSROOM = "DELETE_CLASSROOM";
export const ADD_CLASSROOM = "ADD_CLASSROOM";

// subject
export const GET_LIST_SUBJECT = "GET_LIST_SUBJECT";
export const UPDATE_SUBJECT = "UPDATE_SUBJECT";
export const DELETE_SUBJECT = "DELETE_SUBJECT";
export const ADD_SUBJECT = "ADD_SUBJECT";
export const GET_LIST_SUBJECT_NOT_PAGINATION =
    "GET_LIST_SUBJECT_NOT_PAGINATION";

// registrationSubject
export const GET_LIST_REGISTRATION_SUBJECT = "GET_LIST_REGISTRATION_SUBJECT";
export const UPDATE_REGISTRATION_SUBJECT = "UPDATE_REGISTRATION_SUBJECT";
export const DELETE_REGISTRATION_SUBJECT = "DELETE_REGISTRATION_SUBJECT";
export const ADD_REGISTRATION_SUBJECT = "ADD_REGISTRATION_SUBJECT";
